version: '2.2'

name: swagger

services:

  editor:
    image: swaggerapi/swagger-editor:latest    
    restart: unless-stopped
    ports:
      - 32769:80
      - 32768:8080

  ui:
    image: swaggerapi/swagger-generator:latest 
    restart: unless-stopped
    environment:
      - GENERATOR_HOST=http://${HOSTNAME}
    ports:
      - 32770:80 
      
  validator:
    image: 	swaggerapi/swagger-validator:latest
    restart: unless-stopped
    ports:
      - 32771:8080